/* Generated by Cython 0.23.4 */

#ifndef __PYX_HAVE__openmmlib__fastContacts
#define __PYX_HAVE__openmmlib__fastContacts


#ifndef __PYX_HAVE_API__openmmlib__fastContacts

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyObject) *tonumpyarray(int *, PY_LONG_LONG);

#endif /* !__PYX_HAVE_API__openmmlib__fastContacts */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initfastContacts(void);
#else
PyMODINIT_FUNC PyInit_fastContacts(void);
#endif

#endif /* !__PYX_HAVE__openmmlib__fastContacts */
